allowBuilds:
  esbuild: false
  simple-git-hooks: false
minimumReleaseAgeExclude:
  - "@playwright/test@1.62.1"
  - brace-expansion@5.0.9
  - flatted@3.4.4
  - playwright-core@1.62.1
  - playwright@1.62.1
  - recast@0.23.17
  - vite@8.2.0
  - "@amamo/verso-darwin-arm64@1.0.0-rc.3"
  - "@amamo/verso-darwin-x64@1.0.0-rc.3"
  - "@amamo/verso-linux-arm64@1.0.0-rc.3"
  - "@amamo/verso-linux-x64@1.0.0-rc.3"
  - "@amamo/verso-win32-x64@1.0.0-rc.3"
  - "@amamo/verso@1.0.0-rc.3"
  - lint-staged@17.3.0
